### ISSUE TITLE
Calling Query SkuDetails causes crash

### ISSUE THREAD

**Issue by PizzaPie144** [kulichin/UnrealAndroidPlayBilling#1]
Calling Query SkuDetails causes crash with error: 

Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 13251 (PlayBillingLibr)

PS: do have same issue with OnlineSubsystem GooglePlay buildin plugin. (though  there it crash only in armv7 build not arm64)

**Comment by kulichin** [comment]
Hi. I can't reproduce this crash. Can you provide the crash log?

**Comment by PizzaPie144** [comment]
[errorLog.txt](https://github.com/kulichin/UnrealAndroidPlayBilling/files/7339949/errorLog.txt)

Only kept the relative error in. It is filtered by package name.

**Comment by kulichin** [comment]
I added some conditionals checks, which should be fix that.
