### ISSUE TITLE
Typo in wiki?

### ISSUE THREAD

**Issue by bitporters** [kulichin/UnrealAndroidPlayBilling#2]
Add **GooglePlayBilling** dependency to PublicDependencyModuleNames in your {ProjectName}.Build.cs file (located in Source\{ProjectName}\ directory).

Don't you mean

PublicDependencyModuleNames.Add("AndroidPlayBilling");

**Comment by kulichin** [comment]
Yeah. Thanks for noticing, I have updated this.
